version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: sudo apt-get install -y libgeos-dev
      - run: make build
      - run: go test -v ./...
